version: "3.0"
services:
  kafka-producer:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "kafka-producer"
      MODULE_TYPE: "Output"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      TOPIC: "kafka-topic"
      BOOTSTRAP_SERVERS: "localhost:9092"
      CLIENT_ID: "kafka-producer-module"
      PARTITION: ""
      IS_FLUSHED: "False"
    ports:
      - 80:80
